<?php
/**
 * LSM Sports Theme functions and definitions
 */

if (!defined('_S_VERSION')) {
    define('_S_VERSION', '1.0.0');
}

/**
 * Sets up theme defaults and registers support for various WordPress features.
 */
function lsm_sports_setup() {
    // Add default posts and comments RSS feed links to head.
    add_theme_support('automatic-feed-links');

    // Let WordPress manage the document title.
    add_theme_support('title-tag');

    // Enable support for Post Thumbnails on posts and pages.
    add_theme_support('post-thumbnails');

    // This theme uses wp_nav_menu() in one location.
    register_nav_menus(
        array(
            'menu-1' => esc_html__('Primary', 'lsm-sports'),
        )
    );

    // Switch default core markup for search form, comment form, and comments
    // to output valid HTML5.
    add_theme_support(
        'html5',
        array(
            'search-form',
            'comment-form',
            'comment-list',
            'gallery',
            'caption',
            'style',
            'script',
        )
    );

    // Set up the WordPress core custom background feature.
    add_theme_support(
        'custom-background',
        apply_filters(
            'lsm_sports_custom_background_args',
            array(
                'default-color' => 'ffffff',
                'default-image' => '',
            )
        )
    );

    // Add theme support for selective refresh for widgets.
    add_theme_support('customize-selective-refresh-widgets');

    // Add support for core custom logo.
    add_theme_support(
        'custom-logo',
        array(
            'height'      => 250,
            'width'       => 250,
            'flex-width'  => true,
            'flex-height' => true,
        )
    );

    // Add support for wide and full alignment
    add_theme_support('align-wide');

    // Add support for editor styles
    add_theme_support('editor-styles');

    // Add support for responsive embedded content
    add_theme_support('responsive-embeds');
}
add_action('after_setup_theme', 'lsm_sports_setup');

/**
 * Set the content width in pixels, based on the theme's design and stylesheet.
 */
function lsm_sports_content_width() {
    $GLOBALS['content_width'] = apply_filters('lsm_sports_content_width', 640);
}
add_action('after_setup_theme', 'lsm_sports_content_width', 0);

/**
 * Register widget area.
 */
function lsm_sports_widgets_init() {
    register_sidebar(
        array(
            'name'          => esc_html__('Sidebar', 'lsm-sports'),
            'id'            => 'sidebar-1',
            'description'   => esc_html__('Add widgets here.', 'lsm-sports'),
            'before_widget' => '<section id="%1$s" class="widget bg-white rounded-lg shadow-md p-6 mb-6 %2$s">',
            'after_widget'  => '</section>',
            'before_title'  => '<h2 class="widget-title text-xl font-semibold text-gray-900 mb-4">',
            'after_title'   => '</h2>',
        )
    );
}
add_action('widgets_init', 'lsm_sports_widgets_init');

/**
 * Enqueue scripts and styles.
 */
function lsm_sports_scripts() {
    // Enqueue the main stylesheet
    wp_enqueue_style('lsm-sports-style', get_stylesheet_uri(), array(), _S_VERSION);
    
    // Enqueue the compiled CSS (this will be generated by our build process)
    wp_enqueue_style(
        'lsm-sports-compiled',
        get_template_directory_uri() . '/dist/css/style.css',
        array(),
        _S_VERSION
    );

    // Enqueue navigation script for mobile menu
    wp_enqueue_script(
        'lsm-sports-navigation',
        get_template_directory_uri() . '/js/navigation.js',
        array(),
        _S_VERSION,
        true
    );

    // Enqueue comment reply script
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }
}
add_action('wp_enqueue_scripts', 'lsm_sports_scripts');

/**
 * Add custom classes to navigation menu links
 */
function lsm_sports_nav_menu_link_attributes($atts, $item, $args) {
    if (isset($args->link_class)) {
        $atts['class'] = $args->link_class;
    }
    return $atts;
}
add_filter('nav_menu_link_attributes', 'lsm_sports_nav_menu_link_attributes', 10, 3);

/**
 * Custom template tags for this theme.
 */
require get_template_directory() . '/inc/template-tags.php';

/**
 * Functions which enhance the theme by hooking into WordPress.
 */
require get_template_directory() . '/inc/template-functions.php';

/**
 * Customizer additions.
 */
require get_template_directory() . '/inc/customizer.php';

/**
 * Add custom image sizes
 */
function lsm_sports_custom_image_sizes() {
    add_image_size('lsm-card-thumb', 400, 250, true);
    add_image_size('lsm-hero', 1200, 600, true);
}
add_action('after_setup_theme', 'lsm_sports_custom_image_sizes');

/**
 * Custom excerpt length
 */
function lsm_sports_excerpt_length($length) {
    return 20;
}
add_filter('excerpt_length', 'lsm_sports_excerpt_length', 999);


/**
 * Add custom classes to body
 */
function lsm_sports_body_classes($classes) {
    // Add TailwindCSS classes
    $classes[] = 'font-sans';
    $classes[] = 'antialiased';
    // $classes[] = 'pt-24'; // Add top padding for fixed navbar
    
    // Adds a class of hfeed to non-singular pages.
    if (!is_singular()) {
        $classes[] = 'hfeed';
    }

    // Adds a class of no-sidebar when there is no sidebar present.
    if (!is_active_sidebar('sidebar-1')) {
        $classes[] = 'no-sidebar';
    }
    
    return $classes;
}
add_filter('body_class', 'lsm_sports_body_classes');

/**
 * Disable WordPress default styles that might conflict with TailwindCSS
 */
function lsm_sports_dequeue_styles() {
    // wp_dequeue_style('wp-block-library');
    // wp_dequeue_style('wp-block-library-theme');
    // wp_dequeue_style('wc-block-style');   
}
add_action('wp_enqueue_scripts', 'lsm_sports_dequeue_styles', 100);

/**
 * Add editor styles for Gutenberg
 */
function lsm_sports_add_editor_styles() {
    add_editor_style('dist/css/editor-style.css');
}
add_action('admin_init', 'lsm_sports_add_editor_styles');
